---
- name: Set Dark Theme
  ansible.builtin.command: gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
  become: true
  become_user: "{{ username }}"
  changed_when: true

- name: Set Time Format
  ansible.builtin.command: gsettings set org.gnome.desktop.interface clock-format 12h
  become: true
  become_user: "{{ username }}"
  changed_when: true

- name: Disable Window Anamations
  ansible.builtin.command: gsettings set org.gnome.desktop.interface enable-animations false
  become: true
  become_user: "{{ username }}"
  changed_when: true

- name: Add Maximize Minimize and Close
  ansible.builtin.command: gsettings set org.gnome.desktop.wm.preferences button-layout ":minimize,maximize,close"
  become: true
  become_user: "{{ username }}"
  changed_when: true

- name: Get Terminal Profile Default Settings
  ansible.builtin.command: gsettings get org.gnome.Terminal.ProfilesList default
  register: term
  become: true
  become_user: "{{ username }}"
  changed_when: false

- name: Display Terminal Profile
  ansible.builtin.debug:
    msg: "{{ term.stdout }}"

- name: Set Terminal Font
  ansible.builtin.command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ term.stdout }}/ font 'Monospace 14'"
  become: true
  become_user: "{{ username }}"
  changed_when: true

- name: Set Terminal Disable System Font
  ansible.builtin.command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ term.stdout }}/ use-system-font false"
  become: true
  become_user: "{{ username }}"
  changed_when: true

- name: Set Terminal Disable Bell Font
  ansible.builtin.command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ term.stdout }}/ audible-bell false"
  become: true
  become_user: "{{ username }}"
  changed_when: true

- name: Set Terminal Disable Color Themes
  ansible.builtin.command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ term.stdout }}/ use-theme-colors false"
  become: true
  become_user: "{{ username }}"
  changed_when: true

- name: Set Terminal BG Color
  ansible.builtin.command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ term.stdout }}/ background-color '#000000'"
  become: true
  become_user: "{{ username }}"
  changed_when: true

- name: Set Terminal FG Color
  ansible.builtin.command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ term.stdout }}/ foreground-color '#AFAFAF'"
  become: true
  become_user: "{{ username }}"
  changed_when: true

- name: Set Terminal Scrollbar Policy
  ansible.builtin.command: "gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:{{ term.stdout }}/ scrollbar-policy never"
  become: true
  become_user: "{{ username }}"
  changed_when: true
