---
- include_tasks: repo.yml
- include_tasks: packages.yml
- include_tasks: services.yml
- include_tasks: gsettings.yml

- name: Setting Graphical Target
  shell: systemctl set-default graphical.target

- debug:
    msg: "Please reboot this machine to enable Gnome"