---
- include_tasks: repo.yml

- name: Install common workstation packages
  dnf:
    name:
      - '@Fedora Workstation'
      - gnome-tweak-tool
      - ffmpeg
      - direnv
      - nmon
      - tlp
      - tlp-rdw
      - vlc
      - google-chrome-stable
      - terraform
      - vault
      - consul
      - nomad
      - waypoint
      - vagrant
      - VirtualBox
    disable_gpg_check: yes
    state: present

- name: Enable TLP
  service:
    name: tlp
    enabled: yes
    state: started