galaxy_info:
  author: Michael Tharpe
  description: Basic Fedora Server
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - 20.04

  galaxy_tags: []

dependencies: []
