---
- name: Create local group to contain new users
  ansible.windows.win_group:
    name: LocalGroup
    description: Allow access to C:\Development folder

- name: Create local user
  ansible.windows.win_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups: LocalGroup
    update_password: false
    password_never_expires: true
  loop:
    - name: tharpem
      password: Ch@ng3M3
    - name: tharpea
      password: Ch@ng3M3
