---
- include_tasks: repo.yml

- name: Install Common Packages
  dnf:
    name:
      - direnv
      - vim
      - wget
      - unzip
      - curl
      - nmon
      - terraform
      - vault
      - consul
      - nomad
      - waypoint
      - vagrant
      - VirtualBox
    disable_gpg_check: yes
    state: present