---
- name: Include repository tasks
  ansible.builtin.include_tasks: repo.yml
- name: Install Common Packages
  ansible.builtin.dnf:
    name:
      - wget
      - unzip
      - curl
      - nmon
      - terraform
      - vault
      - consul
      - nomad
      - waypoint
    disable_gpg_check: true
    state: present
