# -*- mode: ruby -*-
# vi: set ft=ruby :

VAULT_DEMO_VERSION = '1.6.1'.freeze

Vagrant.configure(2) do |config|
  config.vm.box = 'generic/ubuntu2004'

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision 'shell', path: './scripts/install-consul.sh'
  config.vm.provision 'shell', path: './scripts/install-vault.sh'
  config.vm.provision 'file', source: './config_files/vault.service', destination: '/tmp/vault.service'
  config.vm.provision 'file', source: './config_files/consul.service', destination: '/tmp/consul.service'
  config.vm.provision 'shell', inline: 'sudo mv /tmp/vault.service /etc/systemd/system && sudo mv /tmp/consul.service /etc/systemd/system'

  config.vm.define 'v1' do |v1|
    v1.vm.hostname = 'v1'
    v1.vm.network 'private_network', ip: '172.20.20.10'
    v1.vm.provision 'file', source: './config_files/v1/init-vault.sh', destination: 'init-vault.sh'
    v1.vm.provision 'file', source: './config_files/v1/vault.hcl', destination: '/tmp/vault.hcl'
    v1.vm.provision 'file', source: './config_files/v1/consul.json', destination: '/tmp/consul.json'
    v1.vm.provision 'shell', inline: 'sudo mv /tmp/vault.hcl /etc/vault.d && sudo mv /tmp/consul.json /etc/consul.d && chmod +x init-vault.sh'
    v1.vm.provision 'shell', path: './scripts/v1/setup-vault.sh'
  end

  config.vm.define 'v2' do |v2|
    v2.vm.hostname = 'v2'
    v2.vm.network 'private_network', ip: '172.20.20.11'
    v2.vm.provision 'file', source: './config_files/v2/init-vault.sh', destination: 'init-vault.sh'
    v2.vm.provision 'file', source: './config_files/v2/vault.hcl', destination: '/tmp/vault.hcl'
    v2.vm.provision 'file', source: './config_files/v2/consul.json', destination: '/tmp/consul.json'
    v2.vm.provision 'shell', inline: 'sudo mv /tmp/vault.hcl /etc/vault.d && sudo mv /tmp/consul.json /etc/consul.d && chmod +x init-vault.sh'
    v2.vm.provision 'shell', path: './scripts/v2/setup-vault.sh'
  end

  config.vm.define 'v3' do |v3|
    v3.vm.hostname = 'v3'
    v3.vm.network 'private_network', ip: '172.20.20.12'
    v3.vm.provision 'file', source: './config_files/v3/init-vault.sh', destination: 'init-vault.sh'
    v3.vm.provision 'file', source: './config_files/v3/vault.hcl', destination: '/tmp/vault.hcl'
    v3.vm.provision 'file', source: './config_files/v3/consul.json', destination: '/tmp/consul.json'
    v3.vm.provision 'shell', inline: 'sudo mv /tmp/vault.hcl /etc/vault.d && sudo mv /tmp/consul.json /etc/consul.d && chmod +x init-vault.sh'
    v3.vm.provision 'shell', path: './scripts/v3/setup-vault.sh'
  end
end
