# -*- mode: ruby -*-
# vi: set ft=ruby :

VAULT_DEMO_VERSION = '1.5.5'.freeze

Vagrant.configure(2) do |config|
  config.vm.box = 'generic/ubuntu1804'
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provision 'shell', path: './scripts/install-vault.sh'
  config.vm.provision 'file', source: './config_files/vault.service', destination: '/tmp/vault.service'
  config.vm.provision 'shell', inline: 'sudo mv /tmp/vault.service /etc/systemd/system'

  config.vm.define 'v1' do |v1|
    v1.vm.hostname = 'v1'
    v1.vm.network 'private_network', ip: '172.20.20.10'
    v1.vm.provision 'file', source: './config_files/v1/vault.hcl', destination: '/tmp/vault.hcl'
    v1.vm.provision 'shell', inline: 'sudo mv /tmp/vault.hcl /etc/vault.d'
    v1.vm.provision 'shell', path: './scripts/v1/setup-vault.sh'
  end

  # config.vm.define 'v2' do |v2|
  #   v2.vm.hostname = 'v2'
  #   v2.vm.network 'private_network', ip: '172.20.20.11'
  #   v2.vm.provision 'file', source: './config_files/v2/vault.hcl', destination: '/tmp/vault.hcl'
  #   v2.vm.provision 'shell', inline: 'sudo mv /tmp/vault.hcl /etc/vault.d'
  #   v2.vm.provision 'shell', path: './scripts/v2/setup-vault.sh'
  # end

  # config.vm.define 'v3' do |v3|
  #   v3.vm.hostname = 'v3'
  #   v3.vm.network 'private_network', ip: '172.20.20.12'
  #   v3.vm.provision 'file', source: './config_files/v3/vault.hcl', destination: '/tmp/vault.hcl'
  #   v3.vm.provision 'shell', inline: 'sudo mv /tmp/vault.hcl /etc/vault.d'
  #   v3.vm.provision 'shell', path: './scripts/v3/setup-vault.sh'
  # end
end
