# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'generic/ubuntu1804'
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provision 'shell', run: 'once', inline: <<-SHELL
    if [ ! -d ansible-ubuntu-base ]; then
      sudo apt-get update
      sudo apt-get upgrade -y --auto-remove
      sudo apt-get install ansible -y
      git clone https://github.com/mtharpe/ansible-ubuntu-base.git
    else
      cd ansible-ubuntu-base && git pull
    fi
   SHELL

  config.vm.provision 'chef_zero' do |chef|
    chef.arguments = '--chef-license accept'
    chef.cookbooks_path = './cookbooks'
    chef.nodes_path = './nodes'
    chef.add_recipe 'chef-linux-base-recipe'
  end
end