# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'generic/ubuntu1710'
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.provision 'shell', inline: <<-SHELL
    sudo apt-get update
    sudo apt-get upgrade -y
  SHELL
end
