---
- name: Include repository tasks
  ansible.builtin.include_tasks: repo.yml
- name: Install Common Packages
  ansible.builtin.apt:
    name:
      - wget
      - nmon
      - direnv
      - tmux
      - unzip
      - curl
      - terraform
      - vault
      - consul
      - nomad
    update_cache: true
    state: present
