# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINE_NAME = 'centos-8'.freeze

# Config engine (Ansible or Chef)
CONFIG_ENGINE = 'ansible'.freeze

# Ansible global controls
ANSIBLE_PLAYBOOK = 'ansible-centos-base'.freeze
ANSIBLE_ROLE = 'server'.freeze
ANSIBLE_SETUP_FILE = 'setup_server.yml'.freeze

Vagrant.configure("2") do |config|
  config.vm.hostname = MACHINE_NAME
  config.vm.box = "generic/centos8"
  config.vm.provider :libvirt do |domain|
      domain.memory = 2048
      domain.cpus = 1
      domain.nested = true
  # config.vm.network :private_network, :ip => '10.20.30.40'
  # config.vm.network :public_network, :ip => '10.20.30.41'
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  end

  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.storage_pool_name = "default"
    libvirt.snapshot_pool_name = "default"
    # libvirt.default_prefix = 'vagrant-'
    # libvirt.qemu_use_session = true
    # libvirt.host = "localhost"
    # libvirt.connect_via_ssh = false
    # libvirt.username = "root"
    # libvirt.password = "secret"
  end

  if CONFIG_ENGINE == 'ansible'
    config.vm.provision 'ansible' do |ansible|
      ansible.playbook = "ansible/#{ANSIBLE_PLAYBOOK}/#{ANSIBLE_ROLE}/#{ANSIBLE_SETUP_FILE}"
    end
  else
    config.vm.provision 'shell', inline: <<-SHELL
      sudo dnf upgrade -y
    SHELL
  end
end
