# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINE_NAME = 'centos-8'.freeze

Vagrant.configure(2) do |config|
  config.vm.box = 'generic/centos8'
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.network :private_network, auto_network: true
  config.vm.hostname = MACHINE_NAME
  # config.vm.network "forwarded_port", guest: 9090, host: 9090
  # config.vm.network 'private_network', type: 'dhcp'
  # config.vm.network 'public_network', type: 'dhcp', bridge: 'enp0s31f6'

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.provider 'virtualbox' do |v|
    v.gui = false
    v.name = MACHINE_NAME
    v.cpus = 1
    v.memory = 4096
    v.linked_clone = false
    config.vm.box_check_update = false
    v.check_guest_additions = true
    v.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root', '1']
  end

  config.vm.provision 'chef_zero' do |chef|
    chef.arguments = '--chef-license accept'
    chef.cookbooks_path = './cookbooks'
    chef.nodes_path = './nodes'
    chef.add_recipe 'chef-linux-base-recipe'
  end
end