version: 2.1
description: Lint shell scripts and YAML

executors:
  shellcheck:
    docker:
      - image: koalaman/shellcheck-alpine:stable
  python:
    docker:
      - image: cimg/python:3.12

jobs:
  shellcheck:
    executor: shellcheck
    steps:
      - checkout
      - run:
          name: shellcheck (errors only) on bin/ scripts
          command: |
            find bin -type f -print0 \
              | xargs -0 -r -n1 shellcheck -S error -x

  yamllint:
    executor: python
    steps:
      - checkout
      - run:
          name: Install yamllint
          command: python -m pip install --upgrade pip yamllint
      - run:
          name: yamllint
          command: yamllint .

workflows:
  validate:
    jobs:
      - shellcheck
      - yamllint
