---
- name: Setup Workstation
  hosts: all
  become: true
  gather_facts: true

  vars:
    username: vagrant

  tasks:
    - name: Include main tasks
      ansible.builtin.include_tasks: tasks/main.yml
