galaxy_info:
  author: Michael Tharpe
  description: Basic Centos Server
  license: license (GPL-2.0-or-later, MIT, etc)
  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
        - 7
        - 8

  galaxy_tags: []

dependencies: []
