# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINE_NAME = 'windows-2019'.freeze

Vagrant.configure(2) do |config|
  config.vm.box = 'StefanScherer/windows_2019'
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.network :private_network, auto_network: true
  config.vm.hostname = MACHINE_NAME
  # config.vm.network 'forwarded_port', guest: 9090, host: 9090
  config.vm.network 'private_network', type: 'dhcp'
  config.vm.network 'public_network', type: 'dhcp', bridge: 'enp0s31f6'

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.provider 'virtualbox' do |v|
    v.gui = true
    v.name = MACHINE_NAME
    v.cpus = 1
    v.memory = 4096
    v.linked_clone = false
    config.vm.box_check_update = false
    v.check_guest_additions = true
  end

  # if Vagrant.has_plugin?('vagrant-cachier')
  #   config.cache.scope = :machine
  #   config.cache.synced_folder_opts = {
  #     type: :nfs,
  #     mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
  #   }
  # end

  # config.vm.provision 'shell', inline: <<-SHELL
  #   sudo dnf upgrade -y
  #   sudo dnf install wget curl git dnf-automatic cockpit cockpit-bridge cockpit-composer cockpit-kdump cockpit-networkmanager cockpit-packagekit cockpit-podman cockpit-selinux cockpit-sosreport cockpit-storaged cockpit-system cockpit-ws -y
  #   sudo systemctl enable --now cockpit.socket
  #   sudo firewall-cmd --add-service=cockpit
  #   sudo firewall-cmd --add-service=cockpit --permanent
  # SHELL
end