---
# - name: Install Chef Workstation
#   dnf:
#     name: "https://packages.chef.io/files/stable/chef-workstation/20.10.168/el/8/chef-workstation-20.10.168-1.el7.x86_64.rpm"
#     disable_gpg_check: yes
#     state: present

- name: Install common workstation packages
  yum:
    name:
      - "@Workstation"
      - "@Development Tools"
      - "@GNOME Applications"
      - "@Office Suite and Productivity"
      - google-chrome-stable
      - slack
      - gnome-tweaks
      - code
      - azure-cli
      - tlp
      - tlp-rdw
      - terraform
      - vault
      - consul
      - nomad
      - waypoint
    disable_gpg_check: yes
    state: present