---
- include_tasks: security.yml
- include_tasks: updates.yml

- name: Install Common Packages
  win_chocolatey:
    name:
      - googlechrome
      - 7zip
      - notepadplusplus
      - git
      - sysinternals
      - ccleaner
      - vscode
      - awscli
      - winscp
    state: present