# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = 'generic/centos7'
  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision 'shell', inline: <<-SHELL
    sudo yum upgrade -y
  SHELL

  config.vm.provision 'chef_zero' do |chef|
    chef.arguments = '--chef-license accept'
    chef.cookbooks_path = './cookbooks'
    chef.nodes_path = './nodes'
    chef.add_recipe 'chef-linux-base-recipe'
  end
end
