# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINE_NAME = 'fedora-workstation'.freeze

# Config engine (Ansible)
# CONFIG_ENGINE = 'ansible'.freeze
 CONFIG_ENGINE = 'nothing'.freeze

# Ansible global controls
# ANSIBLE_PLAYBOOK = 'ansible-fedora-base'.freeze
# ANSIBLE_ROLE = 'workstation'.freeze
# ANSIBLE_SETUP_FILE = 'setup_workstation.yml'.freeze

Vagrant.configure(2) do |config|
  config.vm.box = 'generic/fedora34'
  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vm.network :private_network, auto_network: true
  config.vm.hostname = MACHINE_NAME

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.vm.provider 'virtualbox' do |v|
    v.gui = true
    v.name = MACHINE_NAME
    v.cpus = 1
    v.memory = 4096
    v.linked_clone = false
    config.vm.box_check_update = false
    v.check_guest_additions = true
    v.customize ['setextradata', :id, 'VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root', '1']
  end

  if CONFIG_ENGINE == 'ansible'
    config.vm.provision 'ansible' do |ansible|
      ansible.playbook = "ansible/#{ANSIBLE_PLAYBOOK}/#{ANSIBLE_ROLE}/#{ANSIBLE_SETUP_FILE}"
    end
  else
    config.vm.provision 'shell', inline: <<-SHELL
      sudo dnf upgrade -y
      sudo dnf -y groupinstall "Fedora Workstation" GNOME
      sudo systemctl enable gdm.service
      sudo systemctl start gdm.service
    SHELL
  end
end
