# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify a Consul version
CONSUL_DEMO_VERSION = '1.8.5'.freeze
VAGRANTFILE_API_VERSION = '2'.freeze

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'generic/ubuntu1804'
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  config.vm.provision 'shell', path: './scripts/install-consul.sh'
  config.vm.provision 'file', source: './config_files/resolved.conf', destination: '/tmp/resolved.conf'
  config.vm.provision 'shell', inline: 'sudo mv /tmp/resolved.conf /etc/systemd/'

  config.vm.define 'n1' do |n1|
    n1.vm.hostname = 'n1'
    n1.vm.network 'private_network', ip: '172.20.20.10'
    n1.vm.provision 'file', source: './config_files/consul.service', destination: '/tmp/consul.service'
    n1.vm.provision 'file', source: './config_files/consul_servers/n1-consul-config.hcl', destination: '/tmp/consul.hcl'
    n1.vm.provision 'shell', inline: 'sudo mv /tmp/consul.service /etc/systemd/system/ && sudo mv /tmp/consul.hcl /etc/consul.d/'
    n1.vm.provision 'shell', path: './scripts/n1.sh'
    n1.vm.provision 'shell', inline: 'sudo reboot now'
  end

  config.vm.define 'n2' do |n2|
    n2.vm.hostname = 'n2'
    n2.vm.network 'private_network', ip: '172.20.20.11'
    n2.vm.provision 'file', source: './config_files/consul.service', destination: '/tmp/consul.service'
    n2.vm.provision 'file', source: './config_files/consul_servers/n2-consul-config.hcl', destination: '/tmp/consul.hcl'
    n2.vm.provision 'shell', inline: 'sudo mv /tmp/consul.service /etc/systemd/system/ && sudo mv /tmp/consul.hcl /etc/consul.d/'
    n2.vm.provision 'shell', path: './scripts/n2.sh'
    n2.vm.provision 'shell', inline: 'sudo reboot now'
  end

  config.vm.define 'n3' do |n3|
    n3.vm.hostname = 'n3'
    n3.vm.network 'private_network', ip: '172.20.20.12'
    n3.vm.provision 'file', source: './config_files/consul.service', destination: '/tmp/consul.service'
    n3.vm.provision 'file', source: './config_files/consul_servers/n3-consul-config.hcl', destination: '/tmp/consul.hcl'
    n3.vm.provision 'shell', inline: 'sudo mv /tmp/consul.service /etc/systemd/system/ && sudo mv /tmp/consul.hcl /etc/consul.d/'
    n3.vm.provision 'shell', path: './scripts/n3.sh'
    n3.vm.provision 'shell', inline: 'sudo reboot now'
  end

  config.vm.define 'web1' do |web1|
    web1.vm.hostname = 'web1'
    web1.vm.network 'private_network', ip: '172.20.20.13'
    web1.vm.provision 'file', source: './config_files/consul_clients/consul-client.service', destination: '/tmp/consul.service'
    web1.vm.provision 'file', source: './config_files/proxy_services/web-proxy.service', destination: '/tmp/consul-web-proxy.service'
    web1.vm.provision 'file', source: './config_files/consul_clients/consul-client.json', destination: '/tmp/consul.json'
    web1.vm.provision 'file', source: './config_files/consul_clients/web.json', destination: '/tmp/web.json'
    web1.vm.provision 'shell', inline: 'sudo mv /tmp/consul.service /etc/systemd/system/ && sudo mv /tmp/consul.json /etc/consul.d/ && sudo mv /tmp/web.json /etc/consul.d && mv /tmp/consul-web-proxy.service /etc/systemd/system'
    web1.vm.provision 'shell', path: './scripts/web.sh'
    web1.vm.provision 'shell', inline: 'sudo reboot now'
  end

  config.vm.define 'web2' do |web2|
    web2.vm.hostname = 'web2'
    web2.vm.network 'private_network', ip: '172.20.20.24'
    web2.vm.provision 'file', source: './config_files/consul_clients/consul-client.service', destination: '/tmp/consul.service'
    web2.vm.provision 'file', source: './config_files/proxy_services/web-proxy.service', destination: '/tmp/consul-web-proxy.service'
    web2.vm.provision 'file', source: './config_files/consul_clients/consul-client.json', destination: '/tmp/consul.json'
    web2.vm.provision 'file', source: './config_files/consul_clients/web.json', destination: '/tmp/web.json'
    web2.vm.provision 'shell', inline: 'sudo mv /tmp/consul.service /etc/systemd/system/ && sudo mv /tmp/consul.json /etc/consul.d/ && sudo mv /tmp/web.json /etc/consul.d && mv /tmp/consul-web-proxy.service /etc/systemd/system'
    web2.vm.provision 'shell', path: './scripts/web.sh'
    web2.vm.provision 'shell', inline: 'sudo reboot now'
  end

  config.vm.define 'db' do |db|
    db.vm.hostname = 'db'
    db.vm.network 'private_network', ip: '172.20.20.15'
    db.vm.provision 'file', source: './config_files/consul_clients/consul-client.service', destination: '/tmp/consul.service'
    db.vm.provision 'file', source: './config_files/proxy_services/db-proxy.service', destination: '/tmp/consul-db-proxy.service'
    db.vm.provision 'file', source: './config_files/consul_clients/consul-client.json', destination: '/tmp/consul.json'
    db.vm.provision 'file', source: './config_files/consul_clients/db.json', destination: '/tmp/db.json'
    db.vm.provision 'file', source: './config_files/mysql/mysql.sql', destination: '/tmp/mysql.sql'
    db.vm.provision 'shell', inline: 'sudo mv /tmp/consul.service /etc/systemd/system/ && sudo mv /tmp/consul.json /etc/consul.d/ && sudo mv /tmp/db.json /etc/consul.d && sudo mv /tmp/consul-db-proxy.service /etc/systemd/system'
    db.vm.provision 'shell', path: './scripts/db.sh'
    db.vm.provision 'shell', inline: 'sudo reboot now'
  end
end
